<a href="https://colab.research.google.com/github/JJnotJimmyJohn/NLPwithPyTorchBook/blob/master/PyTorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Very Basics

In [ ]:
import torch
import torch.nn as nn
import numpy as np

In [ ]:
# randomly initialize a tensor by specifying dimentions
torch.Tensor(2,3)

tensor([[3.2857e-35, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])

In [ ]:
# random number - uniform dist
torch.rand(2,2)

tensor([[0.7899, 0.2560],
        [0.2129, 0.0750]])

In [ ]:
# random number - normal dist
torch.randn(2,2)

tensor([[ 0.3919, -0.6420],
        [-0.4853, -1.1380]])

In [ ]:
# create your own tensor from lists
torch.Tensor([[1,2],
              [3,4]])

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
# create tensor from numpy
np_tensor = np.random.randn(2,3)
print(np_tensor)
torch_tensor = torch.from_numpy(np_tensor)
print(torch_tensor)

[[ 2.10333892 -0.50491519 -0.08688658]
 [-0.80465778 -0.41060038 -0.47890138]]
tensor([[ 2.1033, -0.5049, -0.0869],
        [-0.8047, -0.4106, -0.4789]], dtype=torch.float64)


In [ ]:
# see how different they are in terms of dimensions
print(torch_tensor.view(1,-1))
print(torch_tensor.view(-1))

tensor([[ 2.1033, -0.5049, -0.0869, -0.8047, -0.4106, -0.4789]],
       dtype=torch.float64)
tensor([ 2.1033, -0.5049, -0.0869, -0.8047, -0.4106, -0.4789],
       dtype=torch.float64)


In [ ]:
# tensor has operations along different dimensions
print(torch_tensor.sum(0))
print(torch_tensor.sum(1))

tensor([ 1.2987, -0.9155, -0.5658], dtype=torch.float64)
tensor([ 1.5115, -1.6942], dtype=torch.float64)


In [ ]:
# squeeze
print(torch.ones(0,2))
print(torch.ones(2))
print(torch.ones(1,2))
print(torch.ones(2,1,2))
print(torch.ones(2,1,2).squeeze())
print((torch.ones(2,1,2).squeeze())==(torch.ones(2,2)))
print(torch.equal(torch.ones(2,1,2).squeeze(),torch.ones(2,2)))

tensor([], size=(0, 2))
tensor([1., 1.])
tensor([[1., 1.]])
tensor([[[1., 1.]],

        [[1., 1.]]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[True, True],
        [True, True]])
True


In [ ]:
torch.ones(0,2)

tensor([], size=(0, 2))

In [ ]:
x = torch.ones([5,6],requires_grad=True)
x
y = x+2
y
z = y*y*3
z

tensor([[27., 27., 27., 27., 27., 27.],
        [27., 27., 27., 27., 27., 27.],
        [27., 27., 27., 27., 27., 27.],
        [27., 27., 27., 27., 27., 27.],
        [27., 27., 27., 27., 27., 27.]], grad_fn=<MulBackward0>)

In [ ]:
z.shape

torch.Size([5, 6])

In [ ]:
z.size()

torch.Size([5, 6])

In [ ]:
z.backward(torch.ones(5,6)*2)

In [ ]:
z.backward(torch.tensor([[1.,2.],
                         [2.,2.]]))

In [ ]:
x.grad

tensor([[36., 36., 36., 36., 36., 36.],
        [36., 36., 36., 36., 36., 36.],
        [36., 36., 36., 36., 36., 36.],
        [36., 36., 36., 36., 36., 36.],
        [36., 36., 36., 36., 36., 36.]])

In [ ]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [ ]:
x = torch.randn(3, requires_grad=True)

y = x * 2

In [ ]:
y.data.norm()

tensor(5.1892)

In [ ]:
y=0
for x in [-0.4022, -1.8039, -0.8658]:
  x = x*x
  y = y+x

print(y)

4.16542969
